/**
 * Drizzle helpers for the trial-results cache. One row per case;
 * upserted by the runner on completion, read by the panel on mount.
 *
 * The same row also holds the Defender Handoff (one-pager for the PD)
 * once it's generated by the translator pass.
 */
import { eq } from "drizzle-orm";
import { getDb } from "../db";
import { trialResults } from "../../drizzle/schema";
import type { DefenderHandoff, TrialResult } from "./types";

export async function getTrialResult(caseId: number): Promise<TrialResult | null> {
  const db = getDb();
  const rows = await db
    .select()
    .from(trialResults)
    .where(eq(trialResults.caseId, caseId));
  const row = rows[0];
  if (!row) return null;
  try {
    return JSON.parse(row.result) as TrialResult;
  } catch {
    return null;
  }
}

export async function upsertTrialResult(result: TrialResult): Promise<void> {
  const db = getDb();
  // SQLite UPSERT via INSERT ... ON CONFLICT (cleaner than select-then-insert).
  // Note: leaves `handoff` untouched on update — handoff regen is a
  // separate user action; re-running Take-to-Trial does not invalidate
  // the existing handoff. (The user can regenerate the handoff manually
  // if the verdict changes meaningfully.)
  await db
    .insert(trialResults)
    .values({
      caseId: result.caseId,
      result: JSON.stringify(result),
      completedAt: new Date(),
    })
    .onConflictDoUpdate({
      target: trialResults.caseId,
      set: {
        result: JSON.stringify(result),
        completedAt: new Date(),
      },
    });
}

export async function getHandoff(caseId: number): Promise<DefenderHandoff | null> {
  const db = getDb();
  const rows = await db
    .select({ handoff: trialResults.handoff })
    .from(trialResults)
    .where(eq(trialResults.caseId, caseId));
  const row = rows[0];
  if (!row?.handoff) return null;
  try {
    return JSON.parse(row.handoff) as DefenderHandoff;
  } catch {
    return null;
  }
}

export async function upsertHandoff(
  caseId: number,
  handoff: DefenderHandoff,
): Promise<void> {
  const db = getDb();
  await db
    .update(trialResults)
    .set({ handoff: JSON.stringify(handoff) })
    .where(eq(trialResults.caseId, caseId));
}
